const countriesByArea = [
    { name: "Russia", value: 17098246 },
    { name: "Canada", value: 9984670 },
    { name: "China", value: 9706961 },
    { name: "United States", value: 9372610 },
    { name: "Brazil", value: 8515770 },
    { name: "Australia", value: 7741220 },
    { name: "India", value: 3287263 },
    { name: "Argentina", value: 2780400 },
    { name: "Kazakhstan", value: 2724900 },
    { name: "Algeria", value: 2381741 },
    { name: "Democratic Republic of the Congo", value: 2344858 },
    { name: "Saudi Arabia", value: 2149690 },
    { name: "Mexico", value: 1964375 },
    { name: "Indonesia", value: 1904569 },
    { name: "Sudan", value: 1861484 },
    { name: "Libya", value: 1759540 },
    { name: "Iran", value: 1648195 },
    { name: "Mongolia", value: 1564110 },
    { name: "Peru", value: 1285216 },
    { name: "Chad", value: 1284000 },
    { name: "Niger", value: 1267000 },
    { name: "Angola", value: 1246700 },
    { name: "Mali", value: 1240192 },
    { name: "South Africa", value: 1219090 },
    { name: "Colombia", value: 1141748 },
    { name: "Ethiopia", value: 1104300 },
    { name: "Bolivia", value: 1098581 },
    { name: "Mauritania", value: 1030700 },
    { name: "Egypt", value: 1001450 },
    { name: "Tanzania", value: 945087 },
    { name: "Nigeria", value: 923768 },
    { name: "Venezuela", value: 916445 },
    { name: "Pakistan", value: 881913 },
    { name: "Namibia", value: 824292 },
    { name: "Mozambique", value: 799380 },
    { name: "Turkey", value: 783562 },
    { name: "Chile", value: 756102 },
    { name: "Zambia", value: 752618 },
    { name: "Myanmar", value: 676578 },
    { name: "Afghanistan", value: 652230 },
    { name: "Somalia", value: 637657 },
    { name: "Central African Republic", value: 622984 },
    { name: "Ukraine", value: 603550 },
    { name: "Madagascar", value: 587041 },
    { name: "Botswana", value: 581730 },
    { name: "Kenya", value: 580367 },
    { name: "France", value: 551695 },
    { name: "Yemen", value: 527968 },
    { name: "Thailand", value: 513120 },
    { name: "Spain", value: 505990 },
    { name: "Turkmenistan", value: 488100 },
    { name: "Cameroon", value: 475442 },
    { name: "Papua New Guinea", value: 462840 },
    { name: "Sweden", value: 450295 },
    { name: "Uzbekistan", value: 447400 },
    { name: "Morocco", value: 446550 },
    { name: "Iraq", value: 438317 },
    { name: "Paraguay", value: 406752 },
    { name: "Zimbabwe", value: 390757 },
    { name: "Japan", value: 377975 },
    { name: "Germany", value: 357114 },
    { name: "Republic of the Congo", value: 342000 },
    { name: "Finland", value: 338424 },
    { name: "Vietnam", value: 331212 },
    { name: "Malaysia", value: 330803 },
    { name: "Norway", value: 323802 },
    { name: "Ivory Coast", value: 322463 },
    { name: "Poland", value: 312696 },
    { name: "Oman", value: 309500 },
    { name: "Italy", value: 301336 },
    { name: "Philippines", value: 300000 },
    { name: "Ecuador", value: 283561 },
    { name: "Burkina Faso", value: 274200 },
    { name: "New Zealand", value: 270467 },
    { name: "Gabon", value: 267668 },
    { name: "Western Sahara", value: 266000 },
    { name: "Guinea", value: 245857 },
    { name: "United Kingdom", value: 242495 },
    { name: "Uganda", value: 241550 },
    { name: "Ghana", value: 238535 },
    { name: "Romania", value: 238391 },
    { name: "Laos", value: 236800 },
    { name: "Belarus", value: 207600 },
    { name: "Kyrgyzstan", value: 199951 },
    { name: "Senegal", value: 196722 },
    { name: "Syria", value: 185180 },
    { name: "Cambodia", value: 181035 },
    { name: "Uruguay", value: 176215 },
    { name: "Tunisia", value: 163610 },
    { name: "Suriname", value: 163820 },
    { name: "Bangladesh", value: 147570 },
    { name: "Nepal", value: 147181 },
    { name: "Tajikistan", value: 143100 },
    { name: "Greece", value: 131957 },
    { name: "Nicaragua", value: 130373 },
    { name: "North Korea", value: 120538 },
    { name: "Malawi", value: 118484 },
    { name: "Eritrea", value: 117600 },
    { name: "Benin", value: 112622 },
    { name: "Honduras", value: 112090 },
    { name: "Liberia", value: 111369 },
    { name: "Bulgaria", value: 110879 },
    { name: "Cuba", value: 109884 },
    { name: "Guatemala", value: 108889 },
    { name: "Iceland", value: 103000 }
];

const countriesByPopulation = [
    { name: "India", value: 1463.87 },
    { name: "China", value: 1416.10 },
    { name: "United States", value: 347.28 },
    { name: "Indonesia", value: 285.72 },
    { name: "Pakistan", value: 255.22 },
    { name: "Nigeria", value: 237.53 },
    { name: "Brazil", value: 212.81 },
    { name: "Bangladesh", value: 175.69 },
    { name: "Russia", value: 144.00 },
    { name: "Ethiopia", value: 135.47 },
    { name: "Mexico", value: 128.93 },
    { name: "Japan", value: 125.84 },
    { name: "Philippines", value: 120.00 },
    { name: "Egypt", value: 110.00 },
    { name: "Vietnam", value: 100.00 },
    { name: "Democratic Republic of the Congo", value: 95.00 },
    { name: "Turkey", value: 90.00 },
    { name: "Iran", value: 85.00 },
    { name: "Germany", value: 84.00 },
    { name: "Thailand", value: 70.00 },
    { name: "United Kingdom", value: 68.00 },
    { name: "France", value: 65.00 },
    { name: "Italy", value: 60.00 },
    { name: "Tanzania", value: 59.00 },
    { name: "South Africa", value: 58.00 },
    { name: "Myanmar", value: 55.00 },
    { name: "Kenya", value: 54.00 },
    { name: "South Korea", value: 52.00 },
    { name: "Colombia", value: 51.00 },
    { name: "Spain", value: 47.00 },
    { name: "Uganda", value: 46.00 },
    { name: "Argentina", value: 45.00 },
    { name: "Algeria", value: 44.00 },
    { name: "Sudan", value: 43.00 },
    { name: "Ukraine", value: 41.00 },
    { name: "Iraq", value: 40.00 },
    { name: "Afghanistan", value: 39.00 },
    { name: "Poland", value: 38.00 },
    { name: "Canada", value: 37.74 },
    { name: "Morocco", value: 36.91 },
    { name: "Saudi Arabia", value: 34.81 },
    { name: "Uzbekistan", value: 33.47 },
    { name: "Peru", value: 32.97 },
    { name: "Angola", value: 32.87 },
    { name: "Malaysia", value: 32.37 },
    { name: "Mozambique", value: 31.26 },
    { name: "Ghana", value: 31.07 },
    { name: "Yemen", value: 29.83 },
    { name: "Nepal", value: 29.14 },
    { name: "Venezuela", value: 28.44 },
    { name: "Madagascar", value: 27.69 },
    { name: "Cameroon", value: 26.55 },
    { name: "Ivory Coast", value: 26.38 },
    { name: "North Korea", value: 25.78 },
    { name: "Australia", value: 25.50 },
    { name: "Niger", value: 24.21 },
    { name: "Taiwan", value: 23.82 },
    { name: "Sri Lanka", value: 21.41 },
    { name: "Burkina Faso", value: 20.90 },
    { name: "Mali", value: 20.25 },
    { name: "Romania", value: 19.24 },
    { name: "Malawi", value: 19.13 },
    { name: "Chile", value: 19.12 },
    { name: "Kazakhstan", value: 18.78 },
    { name: "Zambia", value: 18.38 },
    { name: "Guatemala", value: 17.92 },
    { name: "Ecuador", value: 17.64 },
    { name: "Syria", value: 17.50 },
    { name: "Netherlands", value: 17.13 },
    { name: "Senegal", value: 16.74 },
    { name: "Cambodia", value: 16.72 },
    { name: "Chad", value: 16.43 },
    { name: "Somalia", value: 15.89 },
    { name: "Zimbabwe", value: 14.86 },
    { name: "Guinea", value: 13.13 },
    { name: "Rwanda", value: 12.95 },
    { name: "Benin", value: 12.12 },
    { name: "Burundi", value: 11.89 },
    { name: "Tunisia", value: 11.82 },
    { name: "Bolivia", value: 11.67 },
    { name: "Belgium", value: 11.59 },
    { name: "Haiti", value: 11.40 },
    { name: "Cuba", value: 11.33 },
    { name: "South Sudan", value: 11.19 },
    { name: "Dominican Republic", value: 10.85 },
    { name: "Czechia", value: 10.71 },
    { name: "Greece", value: 10.42 },
    { name: "Jordan", value: 10.20 },
    { name: "Portugal", value: 10.20 },
    { name: "Azerbaijan", value: 10.13 },
    { name: "Sweden", value: 10.35 },
    { name: "Honduras", value: 10.13 },
    { name: "United Arab Emirates", value: 10.08 },
    { name: "Hungary", value: 9.74 },
    { name: "Tajikistan", value: 9.73 },
    { name: "Belarus", value: 9.35 },
    { name: "Austria", value: 9.02 },
    { name: "Papua New Guinea", value: 9.01 },
    { name: "Serbia", value: 8.77 },
    { name: "Israel", value: 9.37 },
    { name: "Switzerland", value: 8.90 }
];

const instagramFollowers = 
    [
        { name: "Cristiano Ronaldo", value: 651.11 },
        { name: "Lionel Messi", value: 504.97 },
        { name: "Selena Gomez", value: 421.11 },
        { name: "Dwayne Johnson", value: 394.71 },
        { name: "Kylie Jenner", value: 394.30 },
        { name: "Ariana Grande", value: 380.43 },
        { name: "Kim Kardashian", value: 358.00 },
        { name: "Beyoncé", value: 313.00 },
        { name: "Khloé Kardashian", value: 305.00 },
        { name: "Justin Bieber", value: 295.05 },
        { name: "Kendall Jenner", value: 290.00 },
        { name: "Taylor Swift", value: 283.00 },
        { name: "Virat Kohli", value: 270.00 },
        { name: "Jennifer Lopez", value: 249.00 },
        { name: "Nicki Minaj", value: 227.00 },
        { name: "Neymar Jr", value: 227.00 },
        { name: "Kourtney Kardashian", value: 220.00 },
        { name: "Miley Cyrus", value: 213.00 },
        { name: "Katy Perry", value: 205.00 },
        { name: "Zendaya", value: 180.00 },
        { name: "Kevin Hart", value: 177.00 },
        { name: "Cardi B", value: 164.00 },
        { name: "LeBron James", value: 159.00 },
        { name: "Demi Lovato", value: 154.00 },
        { name: "Rihanna", value: 150.00 },
        { name: "Chris Brown", value: 144.00 },
        { name: "Drake", value: 143.00 },
        { name: "Ellen DeGeneres", value: 137.00 },
        { name: "Kylian Mbappé", value: 122.00 },
        { name: "Billie Eilish", value: 121.00 },
        { name: "Gal Gadot", value: 108.00 },
        { name: "Lalisa Manoban", value: 105.00 },
        { name: "Vin Diesel", value: 103.00 },
        { name: "Shraddha Kapoor", value: 94.20 },
        { name: "Priyanka Chopra", value: 92.50 },
        { name: "Narendra Modi", value: 92.40 },
        { name: "Shakira", value: 91.50 },
        { name: "Snoop Dogg", value: 88.20 },
        { name: "David Beckham", value: 88.00 },
        { name: "Dua Lipa", value: 87.30 },
        { name: "Kim Jennie", value: 86.70 },
        { name: "Alia Bhatt", value: 86.20 },
        { name: "Anushka Sharma", value: 84.00 },
        { name: "Deepika Padukone", value: 83.00 },
        { name: "Kareena Kapoor", value: 82.00 },
        { name: "Jacqueline Fernandez", value: 81.00 },
        { name: "Akshay Kumar", value: 80.00 },
        { name: "Ranveer Singh", value: 79.00 },
        { name: "Hrithik Roshan", value: 78.00 },
        { name: "Chris Hemsworth", value: 77.00 },
        { name: "Emma Watson", value: 76.00 },
        { name: "Tom Holland", value: 75.00 },
        { name: "Robert Downey Jr.", value: 74.00 },
        { name: "Zayn Malik", value: 72.00 },
        { name: "Camila Cabello", value: 71.00 },
        { name: "Shawn Mendes", value: 70.00 },
        { name: "Ed Sheeran", value: 69.00 },
        { name: "Bruno Mars", value: 68.00 },
        { name: "Lady Gaga", value: 67.00 },
        { name: "Adele", value: 66.00 },
        { name: "Harry Styles", value: 65.00 },
        { name: "Niall Horan", value: 64.00 },
        { name: "Louis Tomlinson", value: 63.00 },
        { name: "Liam Payne", value: 62.00 },
        { name: "Megan Thee Stallion", value: 61.00 },
        { name: "Doja Cat", value: 60.00 },
        { name: "Olivia Rodrigo", value: 59.00 },
        { name: "Ava Max", value: 58.00 },
        { name: "Khabane Lame", value: 57.00 },
        { name: "Huda Kattan", value: 55.00 },
        { name: "Lele Pons", value: 54.00 },
        { name: "Charli D'Amelio", value: 53.00 },
        { name: "Addison Rae", value: 51.00 },
        { name: "Luisito Comunica", value: 50.00 },
        { name: "Zach King", value: 49.00 },
        { name: "Chiara Ferragni", value: 48.00 },
        { name: "Logan Paul", value: 47.00 },
        { name: "Hannah Stocking", value: 46.00 },
        { name: "Brent Rivera", value: 45.00 },
        { name: "Gordon Ramsay", value: 44.00 },
        { name: "James Charles", value: 43.00 },
        { name: "PewDiePie", value: 42.00 },
        { name: "MrBeast", value: 41.00 },
        { name: "Bretman Rock", value: 40.00 },
        { name: "Liza Koshy", value: 39.00 },
        { name: "David Dobrik", value: 38.00 },
        { name: "King Bach", value: 37.00 },
        { name: "Sommer Ray", value: 36.00 },
        { name: "Amanda Cerny", value: 35.20 },
        { name: "Dixie D'Amelio", value: 34.80 },
        { name: "Bella Poarch", value: 34.50 },
        { name: "Yuzvendra Chahal", value: 34.20 },
        { name: "Hardik Pandya", value: 33.90 },
        { name: "Camila Coelho", value: 33.50 },
        { name: "Kayla Itsines", value: 33.20 },
        { name: "Michelle Lewin", value: 32.80 },
        { name: "Jen Selter", value: 32.40 },
        { name: "Tammy Hembrow", value: 32.10 },
        { name: "Ulisses Jr", value: 31.80 },
        { name: "Ana Cheri", value: 31.50 },
        { name: "Paige Hathaway", value: 31.20 },
        { name: "Simeon Panda", value: 30.90 },
        { name: "Jeff Seid", value: 30.60 },
        { name: "Kayla Nicole", value: 30.30 },
        { name: "Bradley Martyn", value: 30.00 },
        { name: "Devin Physique", value: 29.70 },
        
    ];
    

const spotifyTop100 = [
    { name: "Blinding Lights", value: 4.764 },
    { name: "Shape of You", value: 4.281 },
    { name: "Someone You Loved", value: 3.843 },
    { name: "Starboy", value: 3.808 },
    { name: "As It Was", value: 3.807 },
    { name: "Sunflower", value: 3.752 },
    { name: "Sweater Weather", value: 3.659 },
    { name: "One Dance", value: 3.572 },
    { name: "Stay", value: 3.503 },
    { name: "Believer", value: 3.369 },
    { name: "Perfect", value: 3.356 },
    { name: "Heat Waves", value: 3.327 },
    { name: "Lovely", value: 3.245 },
    { name: "Dance Monkey", value: 3.233 },
    { name: "Say You Won't Let Go", value: 3.199 },
    { name: "Closer", value: 3.198 },
    { name: "Watermelon Sugar", value: 2.852 },
    { name: "Señorita", value: 2.840 },
    { name: "Something Just Like This", value: 2.816 },
    { name: "Riptide", value: 2.744 },
    { name: "Don't Start Now", value: 2.741 },
    { name: "Take Me to Church", value: 2.725 },
    { name: "Another Love", value: 2.678 },
    { name: "Photograph", value: 2.650 },
    { name: "Counting Stars", value: 2.648 },
    { name: "Lucid Dreams", value: 2.646 },
    { name: "God's Plan", value: 2.615 },
    { name: "Circles", value: 2.612 },
    { name: "Bohemian Rhapsody", value: 2.603 },
    { name: "bad guy", value: 2.594 },
    { name: "Thinking Out Loud", value: 2.587 },
    { name: "Can't Hold Us", value: 2.574 },
    { name: "Shallow", value: 2.564 },
    { name: "goosebumps", value: 2.561 },
    { name: "Yellow", value: 2.560 },
    { name: "Love Yourself", value: 2.547 },
    { name: "Cruel Summer", value: 2.530 },
    { name: "Thunder", value: 2.519 },
    { name: "I Wanna Be Yours", value: 2.513 },
    { name: "All of Me", value: 2.495 },
    { name: "Lean On", value: 2.494 },
    { name: "Happier", value: 2.493 },
    { name: "Stressed Out", value: 2.492 },
    { name: "Faded", value: 2.491 },
    { name: "Let Me Love You", value: 2.490 },
    { name: "7 rings", value: 2.489 },
    { name: "Sorry", value: 2.488 },
    { name: "XO Tour Llif3", value: 2.487 },
    { name: "Don't Let Me Down", value: 2.486 },
    { name: "HUMBLE.", value: 2.485 },
    { name: "Viva La Vida", value: 2.484 },
    { name: "Wake Me Up", value: 2.483 },
    { name: "Without Me", value: 2.482 },
    { name: "Mr. Brightside", value: 2.481 },
    { name: "Every Breath You Take", value: 2.480 },
    { name: "No Role Modelz", value: 2.479 },
    { name: "Do I Wanna Know?", value: 2.478 },
    { name: "Lose Yourself", value: 2.477 },
    { name: "Let Her Go", value: 2.476 },
    { name: "The Less I Know The Better", value: 2.475 },
    { name: "SAD!", value: 2.474 },
    { name: "Sicko Mode", value: 2.473 },
    { name: "drivers license", value: 2.472 },
    { name: "The Hills", value: 2.470 },
    { name: "Paradise", value: 2.469 },
    { name: "Young Dumb & Broke", value: 2.468 },
    { name: "Unstoppable", value: 2.467 },
    { name: "Dynamite", value: 2.466 },
    { name: "Peaches", value: 2.465 },
    { name: "MONTERO (Call Me By Your Name)", value: 2.464 },
    { name: "Old Town Road", value: 2.463 },
    { name: "High Hopes", value: 2.462 },
    { name: "Shivers", value: 2.461 },
    { name: "Levitating", value: 2.460 },
    { name: "abcdefu", value: 2.459 },
    { name: "INDUSTRY BABY", value: 2.458 },
    { name: "Happier Than Ever", value: 2.456 },
    { name: "Save Your Tears", value: 2.455 },
    { name: "Good 4 U", value: 2.454 },
    { name: "Butter", value: 2.453 },
    { name: "Easy On Me", value: 2.452 },
    { name: "Bad Habits", value: 2.450 },
    { name: "Beggin'", value: 2.449 },
    { name: "Cold Heart", value: 2.448 },
    { name: "Enemy", value: 2.447 },
    { name: "Woman", value: 2.446 },
    { name: "Ghost", value: 2.445 },
    { name: "Smells Like Teen Spirit", value: 2.444 },
    { name: "We Don't Talk Anymore", value: 2.440 },
    { name: "The Box", value: 2.439 },
    { name: "Attention", value: 2.438 },
    { name: "No Tears Left to Cry", value: 2.437 },
    { name: "Rockstar", value: 2.436 },
    { name: "Meant to Be", value: 2.435 },
    { name: "Bones", value: 2.434 },
    { name: "Truth Hurts", value: 2.433 },
    { name: "Don't Stop Believin'", value: 2.432 },
    { name: "Poker Face", value: 2.430 },
    { name: "You Right", value: 2.429 },
    { name: "Say So", value: 2.427 },
    { name: "Super Gremlin", value: 2.426 },
    { name: "Stay With Me", value: 2.423 },
    { name: "Love Nwantiti", value: 2.422 }
];

const netflixTop100 = [
    { name: "Red Notice", value: 364.02 },
    { name: "Don't Look Up", value: 359.79 },
    { name: "Bird Box", value: 282.02 },
    { name: "Glass Onion: A Knives Out Mystery", value: 279.74 },
    { name: "The Gray Man", value: 253.87 },
    { name: "The Mother", value: 234.07 },
    { name: "The Adam Project", value: 233.16 },
    { name: "Extraction", value: 231.34 },
    { name: "Purple Hearts", value: 228.69 },
    { name: "The Unforgivable", value: 214.70 },
    { name: "The Irishman", value: 214.57 },
    { name: "The Kissing Booth 2", value: 209.25 },
    { name: "6 Underground", value: 205.47 },
    { name: "Spenser Confidential", value: 197.32 },
    { name: "Enola Holmes", value: 189.90 },
    { name: "Army of the Dead", value: 186.54 },
    { name: "The Old Guard", value: 185.71 },
    { name: "Murder Mystery", value: 169.59 },
    { name: "Troll", value: 155.56 },
    { name: "Blood Red Sky", value: 110.52 },
    { name: "The Platform", value: 108.09 },
    { name: "All Quiet on the Western Front", value: 101.36 },
    { name: "The Midnight Sky", value: 100.00 },
    { name: "Project Power", value: 99.00 },
    { name: "We Can Be Heroes", value: 98.00 },
    { name: "Fatherhood", value: 97.00 },
    { name: "The Guilty", value: 96.00 },
    { name: "Sweet Girl", value: 95.00 },
    { name: "Outside the Wire", value: 94.00 },
    { name: "The Christmas Chronicles: Part Two", value: 93.00 },
    { name: "The Wrong Missy", value: 92.00 },
    { name: "The Kissing Booth 3", value: 91.00 },
    { name: "I Care a Lot", value: 90.00 },
    { name: "He's All That", value: 89.00 },
    { name: "The Mitchells vs. The Machines", value: 88.00 },
    { name: "Army of Thieves", value: 87.00 },
    { name: "Yes Day", value: 86.00 },
    { name: "The Christmas Chronicles", value: 85.00 },
    { name: "The Old Guard 2", value: 84.00 },
    { name: "The Harder They Fall", value: 83.00 },
    { name: "The Woman in the Window", value: 82.00 },
    { name: "Kate", value: 81.00 },
    { name: "The Dig", value: 80.00 },
    { name: "The Devil All the Time", value: 79.00 },
    { name: "The Two Popes", value: 78.00 },
    { name: "The Laundromat", value: 77.00 },
    { name: "The King", value: 76.00 },
    { name: "The Highwaymen", value: 75.00 },
    { name: "The Perfect Date", value: 74.00 },
    { name: "The Willoughbys", value: 73.00 },
    { name: "The Half of It", value: 72.00 },
    { name: "The Lovebirds", value: 71.00 },
    { name: "The Last Days of American Crime", value: 70.00 },
    { name: "The Wrong Missy 2", value: 69.00 },
    { name: "The Princess Switch 3", value: 68.00 },
    { name: "The Knight Before Christmas", value: 67.00 },
    { name: "The Midnight Sky", value: 66.00 },
    { name: "The Out-Laws", value: 65.00 },
    { name: "The Perfect Date", value: 64.00 },
    { name: "The Sea Beast", value: 63.00 },
    { name: "The Trial of the Chicago 7", value: 62.00 },
    { name: "Thunder Force", value: 61.00 },
    { name: "To All the Boys: Always and Forever", value: 60.00 },
    { name: "Triple Frontier", value: 59.00 },
    { name: "Tyler Perry's A Fall From Grace", value: 58.00 },
    { name: "We Can Be Heroes", value: 57.00 },
    { name: "Wish Dragon", value: 56.00 },
    { name: "Yes Day", value: 55.00 },
    { name: "Your Place or Mine", value: 54.00 },
    { name: "You People", value: 53.00 },
    { name: "You Are So Not Invited to My Bat Mitzvah", value: 52.00 },
    { name: "The Adam Project", value: 51.00 },
    { name: "Extraction 2", value: 50.00 },
    { name: "The Wonder", value: 49.00 },
    { name: "The Good Nurse", value: 48.00 },
    { name: "The Swimmers", value: 47.00 },
    { name: "White Noise", value: 46.00 },
    { name: "Slumberland", value: 45.00 },
    { name: "Lady Chatterley's Lover", value: 44.00 },
    { name: "Blonde", value: 43.00 },
    { name: "Lou", value: 42.00 },
    { name: "Do Revenge", value: 41.00 },
    { name: "Day Shift", value: 40.00 },
    { name: "Purple Hearts", value: 39.00 },
    { name: "Carter", value: 38.00 },
    { name: "The Sea Beast", value: 37.00 },
    { name: "Persuasion", value: 36.00 },
    { name: "Hello, Goodbye, and Everything in Between", value: 35.00 },
    { name: "Hustle", value: 34.00 },
    { name: "Interceptor", value: 33.00 },
    { name: "Along for the Ride", value: 32.00 },
    { name: "Choose or Die", value: 31.00 },
    { name: "Metal Lords", value: 30.00 },
    { name: "Apollo 10 1/2", value: 29.00 },
    { name: "Windfall", value: 28.00 },
    { name: "The Adam Project", value: 27.00 },
    { name: "The Weekend Away", value: 26.00 },
    { name: "Against the Ice", value: 25.00 },
    { name: "Texas Chainsaw Massacre", value: 24.00 },
    { name: "The Royal Treatment", value: 23.00 },
    { name: "Home Team", value: 22.00 }
];

const spotifyArtists = [
    { name: "Taylor Swift", value: 100.53 },
    { name: "Bad Bunny", value: 86.88 },
    { name: "Drake", value: 85.18 },
    { name: "The Weeknd", value: 67.27 },
    { name: "Ariana Grande", value: 52.62 },
    { name: "Ed Sheeran", value: 52.24 },
    { name: "Eminem", value: 49.46 },
    { name: "Justin Bieber", value: 47.60 },
    { name: "Billie Eilish", value: 46.24 },
    { name: "Kanye West", value: 45.66 },
    { name: "Post Malone", value: 44.40 },
    { name: "BTS", value: 41.85 },
    { name: "Travis Scott", value: 38.19 },
    { name: "Rihanna", value: 37.87 },
    { name: "Coldplay", value: 37.79 },
    { name: "J Balvin", value: 37.45 },
    { name: "Bruno Mars", value: 35.58 },
    { name: "Kendrick Lamar", value: 36.37 },
    { name: "Dua Lipa", value: 35.31 },
    { name: "Imagine Dragons", value: 34.65 },
    { name: "Juice WRLD", value: 34.26 },
    { name: "David Guetta", value: 32.10 },
    { name: "XXXTENTACION", value: 32.03 },
    { name: "Ozuna", value: 30.37 },
    { name: "Lana Del Rey", value: 30.07 },
    { name: "Maroon 5", value: 29.68 },
    { name: "Khalid", value: 27.97 },
    { name: "Future", value: 27.81 },
    { name: "Lady Gaga", value: 27.70 },
    { name: "Calvin Harris", value: 27.64 },
    { name: "Karol G", value: 27.28 },
    { name: "Beyoncé", value: 26.64 },
    { name: "Rauw Alejandro", value: 26.46 },
    { name: "Shawn Mendes", value: 25.75 },
    { name: "Sam Smith", value: 25.41 },
    { name: "Queen", value: 25.13 },
    { name: "One Direction", value: 24.53 },
    { name: "Linkin Park", value: 24.44 },
    { name: "Harry Styles", value: 24.28 },
    { name: "Adele", value: 24.20 },
    { name: "Anuel AA", value: 24.10 },
    { name: "J. Cole", value: 23.73 },
    { name: "Metro Boomin", value: 23.71 },
    { name: "Chris Brown", value: 23.36 },
    { name: "Shakira", value: 23.32 },
    { name: "Daddy Yankee", value: 23.20 },
    { name: "SZA", value: 23.11 },
    { name: "Arctic Monkeys", value: 22.67 },
    { name: "Peso Pluma", value: 22.00 },
    { name: "The Beatles", value: 21.93 },
    { name: "Doja Cat", value: 21.76 },
    { name: "Olivia Rodrigo", value: 21.53 },
    { name: "Katy Perry", value: 20.84 },
    { name: "Nicki Minaj", value: 20.74 },
    { name: "The Chainsmokers", value: 20.60 },
    { name: "21 Savage", value: 20.51 },
    { name: "Maluma", value: 20.48 },
    { name: "Selena Gomez", value: 20.37 },
    { name: "Morgan Wallen", value: 20.02 },
    { name: "Sia", value: 20.02 },
    { name: "Lil Uzi Vert", value: 19.96 },
    { name: "Marshmello", value: 19.85 },
    { name: "Halsey", value: 18.80 },
    { name: "Tyler, The Creator", value: 18.47 },
    { name: "Twenty One Pilots", value: 18.37 },
    { name: "Miley Cyrus", value: 18.09 },
    { name: "Myke Towers", value: 17.95 },
    { name: "Lil Baby", value: 17.72 },
    { name: "Avicii", value: 17.02 },
    { name: "Junior H", value: 17.56 },
    { name: "Red Hot Chili Peppers", value: 17.50 },
    { name: "OneRepublic", value: 17.31 },
    { name: "Pritam", value: 16.97 },
    { name: "Kygo", value: 16.36 },
    { name: "Farruko", value: 16.59 },
    { name: "Camila Cabello", value: 16.42 },
    { name: "Michael Jackson", value: 16.24 },
    { name: "Frank Ocean", value: 16.04 },
    { name: "Gunna", value: 15.63 },
    { name: "Mac Miller", value: 15.58 },
    { name: "Elton John", value: 15.22 },
    { name: "Lil Peep", value: 15.19 },
    { name: "Pitbull", value: 15.08 },
    { name: "The Neighbourhood", value: 15.00 },
    { name: "Charlie Puth", value: 14.92 },
    { name: "Metallica", value: 14.92 },
    { name: "Sabrina Carpenter", value: 14.20 },
    { name: "Jason Derulo", value: 14.18 },
    { name: "Demi Lovato", value: 13.93 },
    { name: "AC/DC", value: 13.81 },
    { name: "BLACKPINK", value: 13.80 },
    { name: "Romeo Santos", value: 13.78 },
    { name: "Pop Smoke", value: 13.74 },
    { name: "Luis Miguel", value: 13.68 },
    { name: "Ellie Goulding", value: 13.55 },
    { name: "Alan Walker", value: 13.54 },
    { name: "Lil Wayne", value: 13.48 },
    { name: "Tiësto", value: 13.35 },
    { name: "YoungBoy Never Broke Again", value: 13.28 },
    { name: "Feid", value: 13.10 }
];

const mobileApps = [
    { name: "TikTok", value: 825.48 },
{ name: "Instagram", value: 817.49 },
{ name: "Facebook", value: 597.87 },
{ name: "WhatsApp Messenger", value: 564.33 },
{ name: "Temu", value: 516.40 },
{ name: "Telegram", value: 447.77 },
{ name: "CapCut", value: 410.33 },
{ name: "Snapchat", value: 330.55 },
{ name: "Threads", value: 326.75 },
{ name: "WhatsApp Business", value: 294.10 },
{ name: "Facebook Messenger", value: 289.63 },
{ name: "ChatGPT", value: 282.22 },
{ name: "Spotify", value: 244.16 },
{ name: "SHEIN", value: 228.45 },
{ name: "Roblox", value: 203.96 },
{ name: "Amazon Shopping", value: 202.14 },
{ name: "Google One", value: 197.76 },
{ name: "YouTube", value: 191.52 },
{ name: "TikTok Lite", value: 181.43 },
{ name: "Amazon Prime Video", value: 179.03 },
{ name: "Gmail", value: 175.67 },
{ name: "Google Maps", value: 170.32 },
{ name: "Uber", value: 165.56 },
{ name: "Netflix", value: 161.98 },
{ name: "AliExpress", value: 157.23 },
{ name: "Shazam", value: 152.11 },
{ name: "Microsoft Teams", value: 147.74 },
{ name: "Google Photos", value: 143.96 },
{ name: "Netflix Lite", value: 141.23 },
{ name: "Pinterest", value: 137.34 },
{ name: "Skype", value: 91.12 },
{ name: "Spotify Lite", value: 89.24 },
{ name: "Pinterest Lite", value: 88.11 },
{ name: "TikTok Now", value: 86.49 },
{ name: "Yahoo Mail", value: 84.95 },
{ name: "Google Meet", value: 83.14 },
{ name: "Opera Browser", value: 82.01 },
{ name: "Telegram X", value: 80.98 },
{ name: "Snapchat Lite", value: 79.35 },
{ name: "Twitch", value: 78.89 },
{ name: "Facebook Lite", value: 77.52 },
{ name: "Pandora", value: 75.33 },
{ name: "Hotstar", value: 74.22 },
{ name: "Byte", value: 73.11 },
{ name: "Reddit", value: 72.45 },
{ name: "Duolingo", value: 71.23 },
{ name: "Baidu", value: 69.97 },
{ name: "Google Pay", value: 68.14 },
{ name: "Yahoo Sports", value: 67.31 },
{ name: "Apple Music", value: 65.98 },
{ name: "Google News", value: 64.56 },
{ name: "Dropbox", value: 63.22 },
{ name: "Tidal", value: 62.45 },
{ name: "Netflix Kids", value: 61.34 },
{ name: "Grubhub", value: 60.01 },
{ name: "Shazam Lite", value: 58.11 },
{ name: "KineMaster", value: 57.35 },
{ name: "Google Docs", value: 56.71 },
{ name: "Amazon Prime Video Lite", value: 55.92 },
{ name: "VLC Media Player", value: 54.01 },
{ name: "Zoom Lite", value: 53.11 },
{ name: "Pinterest Lens", value: 52.01 },
{ name: "Facebook Gaming", value: 51.34 },
{ name: "Resso", value: 50.21 },
{ name: "DuoLingo Plus", value: 49.88 },
{ name: "AccuWeather", value: 48.99 },
{ name: "Microsoft Word", value: 48.14 },
{ name: "Android Auto", value: 47.65 },
{ name: "eBay", value: 46.21 },
{ name: "Telegram Desktop", value: 45.56 },
{ name: "Fotor", value: 44.88 },
{ name: "Adobe Acrobat Reader", value: 43.35 },
{ name: "Slack", value: 42.76 },
{ name: "Pinterest Trends", value: 41.52 },
{ name: "SoundCloud", value: 40.67 },
{ name: "Google Stadia", value: 39.34 },
{ name: "Wish Local", value: 38.76 },
{ name: "Fitbit", value: 37.54 },
{ name: "Google Play Music", value: 36.42 },
{ name: "Huawei Mobile Services", value: 35.98 },
{ name: "Huawei Mobile Services", value: 35.98 },
{ name: "Zalo", value: 35.12 },
{ name: "Yahoo", value: 34.58 },
{ name: "Google Assistant", value: 34.10 },
{ name: "Adobe Photoshop Express", value: 33.58 },
{ name: "Gmail Lite", value: 33.02 },
{ name: "Amazon Kindle", value: 32.61 },
{ name: "Bing", value: 32.02 },
{ name: "Tumblr", value: 31.61 },
{ name: "DuckDuckGo", value: 31.15 },
{ name: "Steam", value: 30.71 },
{ name: "Redfin", value: 30.14 },
{ name: "Flipkart", value: 29.62 },
{ name: "Wells Fargo", value: 29.10 },
{ name: "Grammarly", value: 28.78 },
{ name: "Nike Training Club", value: 28.44 },
{ name: "Yelp", value: 28.10 },
{ name: "Robinhood", value: 27.56 },
{ name: "Clubhouse", value: 27.02 },
{ name: "Mint", value: 26.68 },
{ name: "McDonald's", value: 26.01 }
];

// Create the gameData object that the game uses
window.gameData = {
    area: {
        title: "Top 100 Countries by Area",
        unit: "km²",
        data: countriesByArea,
        icon: 'fas fa-globe-americas',
        locked: false,
        isTodaysCategory: false,
        targetScore: 200
    },
    population: {
        title: "Top 100 Countries by Population",
        unit: "millionpeople",
        data: countriesByPopulation,
        icon: 'fas fa-users',
        locked: false,
        isTodaysCategory: false,
        targetScore: 200
    },
    spotifyArtists: {
        title: "Top 100 Most Streamed Artists on Spotify",
        unit: "million monthly listeners",
        data: spotifyArtists,
        icon: 'fab fa-spotify',
        locked: true,
        isTodaysCategory: true,
        targetScore: 200
    },
    instagram: {
        title: "Top 100 Most Followed People on Instagram",
        unit: "million followers",
        data: instagramFollowers,
        icon: 'fab fa-instagram',
        locked: true,
        isTodaysCategory: false,
        targetScore: 200
    },
    spotify: {
        title: "Top 100 Most Played Songs on Spotify",
        unit: "billion plays",
        data: spotifyTop100,
        icon: 'fab fa-spotify',
        locked: true,
        isTodaysCategory: false,
        targetScore: 200
    },
    netflix: {
        title: "Top 100 Most Watched Movies on Netflix",
        data: netflixTop100,
        unit: 'M hours',
        icon: 'fa-solid fa-tv',
        locked: true,
        isTodaysCategory: false,
        targetScore: 200
    },
    mobileApps: {
        title: "Top 100 Most Downloaded Mobile Apps in 2024",
        unit: "million downloads",
        data: mobileApps,
        icon: 'fas fa-mobile-alt',
        locked: true,
        isTodaysCategory: false,
        targetScore: 200
    }
};

// Export the categories for use in script.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.gameData;
} 